---
- name: finals-exam
  hosts: all
  tasks:
    - name: Include global variables
      include_vars:
        file: config.yaml

    - name: Install docker for Ubuntu
      include_role:
        name: installpkgubuntu
      vars:
        package:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3
          - python3-pip
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install docker for Ubuntu
      include_role:
        name: installpkgubuntu
      vars:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        filename: "docker-ce"
        package:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        service: docker
        when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install docker Centos
      include_role:
        name: installpkgCentOS
      vars:
        src: "{{ docker_repo }}"
        dest: "/etc/yum.repos.d/docker-ce.repo"
        package:
          - docker-ce
          - python3
          - python3-pip
        service: docker
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Disable firewalld for CentOS
      include_role:
        name: stopfirewalld
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Disable UFW for Ubuntu
      include_role:
        name: stopufw
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: "Pip for installing docker modules"
      include_role:
        name: pipinstall
      vars:
        pippackage: docker

    - name: Create user for docker group
      include_role:
        name: mk_docker_group

    - name: Install and Run ELK
      include_role:
        name: elk_install

    - name: Install and Run Nagios
      include_role:
        name: nagios_install
      vars:
        url: ""
        repo: ""
        package:
          - autoconf
      vars:
        url: ""
        repo: ""
        package: 
          - apache
          - httpd
        service: nagios
      when: ansible_facts['distribution'] = 'Debian'


          


