---
- name: "4.1 | Git clone"
  tags: git,ubuntu,centos
  hosts: git
  tasks:
    - name: Include global variable
      include_vars:
        file: config.yaml

    - name: Install git in Ubuntu
      include_role:
        name: installubuntupkg
      vars:
        package: git
      when: ansible_distribution == 'Ubuntu'

    - name: Install git in CentOS
      include_role:
        name: installcentospkg
      vars:
        package: git
      when: ansible_distribution == 'CentOS'

    - name: Install git in OpenSUSE
      include_role:
        name: installsusepkg
      vars:
        package: git
      when: ansible_facts['os_family'] == 'Suse'

    - name: Git clone
      include_role:
        name: gitclone

- name: "4.2 | Install service"
  tags: ftp,ubuntu,centos,suse
  hosts: ftpserver
  tasks:
    - name: Include global variables
      include_vars:
        file: config.yaml

    - name: Install vsftpd in ubuntu
      include_role:
        name: installubuntupkg
      vars:
        package: vsftpd
        service: vsftpd
      when: ansible_distribution == 'Ubuntu'

    - name: Install vsftpd in CentOS
      include_role:
        name: installcentospkg
      vars:
        package: vsftpd
        service: vsftpd
      when: ansible_distribution == 'CentOS'

    - name: Install vsftpd in Suse
      include_role:
        name: installsusepkg
      vars:
        package: vsftpd
      when: ansible_facts['os_family'] == 'Suse'

    - name: Config vsftpd in Ubuntu
      include_role:
        name: configubuntuftp
      when: ansible_distribution == 'Ubuntu'

    - name: Config vsftpd in centos
      include_role:
        name: configcentosftp
      when: ansible_distribution == 'CentOS'

    - name: Config vsftpd in suse
      include_role:
        name: configsuseftp
      when: ansible_facts['os_family'] == 'Suse'


