---
- name: Start and enable VSFTPD
  service:
    name: vsftpd
    state: started
    enabled: yes

- name: Create FTP User
  user:
    name: "{{ ftp_user }}"
    password: "{{ ftp_password | password_hash('sha512') }}"
    comment: "{{ ftp_comment }}"
    home: /srv/ftp

- name: Create FTP group
  group:
    name: ftpuser
    state: present

- name: Add FTP user to FTP group
  user:
    name: "{{ ftp_user }}"
    groups: ftpuser
    append: yes

- name: Change FTP directory ownership
  file:
    path: /srv/ftp
    state: directory
    group: ftpuser

- name: Copy vsftpd.conf to /etc/vsftpd.comf
  copy:
    src: "{{ vsftpd_opensuse }}"
    dest: /etc/vsftpd.conf
  register: vsftpd_conf

- name: Restart VSFTPD
  service:
    name: vsftpd
    state: restarted
  when: vsftpd_conf.changed

