---
- name: Create docker directory
  file:
    path: docker
    state: directory

- name: Copy from docker dir files to remote
  copy:
    src: docker/
    dest: docker/

- name: Build Nagios stack using Docker image
  docker_image:
    name: "{{ docker_nagios_image_name }}"
    build:
      path: "{{ docker_nagios_dockerfile_path }}"
      pull: no
    state: present
    source: build
  register: nagios_docker_img

- name: Clear iptables routing filter
  shell: iptables -F; iptables -X
  when: elk_nagios_img.changed

- name: Restart nagios
  service:
    name: nagios
    state: restarted

- name: Run Nagios
  docker_container:
    name: "{{ docker_nagios_container_name }}"
    image: "{{ docker_nagios_image_name }}:{{ docker_nagios_image_tag }}"
    state: started
    ports: "{{ nagios_ports }}"
