---
- name: Add apt key
  apt_key:
    url: "{{ url }}"
    state: present
  when: url is defined

- name: add repository
  apt_repository:
    repo: "{{ repo }}"
    state: present
    filename: "{{ filename }}"
  when: repo is defined

- name: Install package
  apt:
    name: "{{ package }}"
    state: latest
    update_cache: yes

- name: start and enable
  service:
    name: "{{ service }}"
    state: started
    enabled: yes
  when: service is defined
